name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          ls build
      - name: Generate API module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          git clone https://user:$GITHUB_TOKEN@github.com/Zealandia-Systems/help-site.git # This works

          cd help-site

          git checkout main

          rm -rf ./
          cp -r ../build ./

          git add ./
          git commit -m"pipeline push"

          git push
