name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run build
      - name: Commit for other repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          git clone https://github.com/Zealandia-Systems/help-site.git

          cd help-site

          cp -r ../build ./

          git config --global user.email "lachlan.alsop@gmail.com"
          git config --global user.name "Lachlan Alsop Pipeline"

          git add ./
          git commit -m"pipeline push"
          
      - name: Commit to other repo
        run: |

          cd help-site
          git push
